import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const raw=fs.readFileSync(new URL('../template/sw.js',import.meta.url),'utf8');
function worker(fetcher){const listeners={},deleted=[],puts=[];let usedCache;const context={URL,Request,Response,fetch:fetcher,caches:{keys:async()=>['roadbook-%2Fone%2F-old','roadbook-%2Ftwo%2F-old'],delete:async key=>deleted.push(key),open:async key=>{usedCache=key;return{match:async()=>new Response('cached'),put:async(...args)=>puts.push(args),addAll:async()=>{}}}},self:{registration:{scope:'https://example.test/one/'},location:{origin:'https://example.test'},clients:{claim:async()=>{}},skipWaiting:async()=>{},addEventListener:(type,callback)=>listeners[type]=callback}};vm.runInNewContext(raw.replace('__PRECACHE__','[]').replace('__VERSION__','new'),context);return{listeners,deleted,puts,get usedCache(){return usedCache;}};}
test('activation only cleans the current roadbook scope',async()=>{const w=worker();let done;w.listeners.activate({waitUntil:p=>done=p});await done;assert.deepEqual(w.deleted,['roadbook-%2Fone%2F-old']);});
test('a failed data response retains the usable offline copy',async()=>{const w=worker(async()=>new Response('missing',{status:404}));let response;w.listeners.fetch({request:new Request('https://example.test/one/travel-data.json'),respondWith:p=>response=p});assert.equal(await(await response).text(),'cached');assert.equal(w.puts.length,0);assert.equal(w.usedCache,'roadbook-%2Fone%2F-new');});
test('online code uses the network while large images can stay cached',async()=>{let network=0;const w=worker(async()=>{network++;return new Response('fresh');});let response;w.listeners.fetch({request:new Request('https://example.test/one/styles.css'),respondWith:p=>response=p});assert.equal(await(await response).text(),'fresh');w.listeners.fetch({request:new Request('https://example.test/one/assets/cover.webp'),respondWith:p=>response=p});assert.equal(await(await response).text(),'cached');assert.equal(network,1);});
test('range requests are left to the browser and never cached as complete files',()=>{const w=worker();let handled=false;w.listeners.fetch({request:new Request('https://example.test/one/video.mp4',{headers:{Range:'bytes=0-100'}}),respondWith:()=>handled=true});assert.equal(handled,false);});
