export const title={en:'Business','zh-CN':'商务'};
export function expenseTotals(expenses=[]) {
  const totals=Object.create(null);let unknown=0;
  for(const expense of expenses){const money=expense.amount;if(!money||!Number.isFinite(money.amount)){unknown++;continue;}const bucket=totals[money.currency]||={known:0,company:0,personal:0,unassigned:0};bucket.known+=money.amount;bucket[['company','personal'].includes(expense.allocation)?expense.allocation:'unassigned']+=money.amount;}
  return {currencies:totals,unknown};
}
export function render({element,data,locale,escapeHTML:E,formatMoney,storageKey}) {
  const zh=locale.startsWith('zh'),L=zh?{heading:'商务议程与费用',agenda:'固定议程',expenses:'费用与凭证',unknown:'尚待确认',budget:'预算上限',known:'已知金额小计',missing:'金额未知项目',receipt:'凭证已收集',note:'凭证勾选仅保存在本浏览器，不表示已提交、批准或报销到账。',policy:'公司政策与个人延住',private:'会议私有地址、联系人与票据原件请保存在发布目录之外。',storage:'无法保存，本次勾选可能在刷新后丢失。',empty:'暂无费用项目。'}:{heading:'Business agenda & expenses',agenda:'Fixed agenda',expenses:'Expenses & receipts',unknown:'Not confirmed',budget:'Budget limit',known:'Known subtotal',missing:'Items with unknown amounts',receipt:'Receipt collected',note:'Receipt checks stay in this browser. They do not mean submitted, approved or reimbursed.',policy:'Company policy & personal extension',private:'Keep private meeting addresses, contacts and original receipts outside the published directory.',storage:'Could not save; checks may be lost on reload.',empty:'No expense items yet.'};
  const business=data.business||{},expenses=business.expenses||[],totals=expenseTotals(expenses);
  let saved={};try{const value=JSON.parse(localStorage.getItem(storageKey)||'{}');if(value&&typeof value==='object'&&!Array.isArray(value))saved=value;}catch{}
  const agenda=(data.days||[]).flatMap(day=>(day.events||[]).filter(e=>e.kind==='meeting').map(e=>`<li><time>${E(day.date)} · ${E(e.timeLabel)}</time><h4>${E(e.title)}</h4><p>${E(e.notes||'')}</p></li>`));
  element.innerHTML=`<div class="section-head"><h2>${E(L.heading)}</h2></div><section class="card"><h3>${E(L.agenda)}</h3><ol class="business-agenda">${agenda.join('')||`<li>${E(L.unknown)}</li>`}</ol></section><section class="card business-expenses"><h3>${E(L.expenses)}</h3><p>${E(L.budget)}: ${E(formatMoney(business.budget,locale)||L.unknown)}</p>${Object.entries(totals.currencies).map(([currency,v])=>`<p>${E(L.known)}: ${E(formatMoney({currency,amount:v.known},locale))}</p>`).join('')}<p>${E(L.missing)}: ${totals.unknown}</p>${expenses.map(e=>`<div class="business-expense"><div><b>${E(e.title)}</b><p>${E(formatMoney(e.amount,locale)||L.unknown)} · ${E(e.allocation||'unknown')}</p></div><label><input type="checkbox" data-receipt="${E(e.id)}" aria-label="${E(L.receipt+': '+e.title)}" ${saved[e.id]===true?'checked':''}>${E(L.receipt)}</label></div>`).join('')||`<p>${E(L.empty)}</p>`}<p class="small muted">${E(L.note)}</p><p data-business-storage role="status" hidden>${E(L.storage)}</p></section><section class="card"><h3>${E(L.policy)}</h3><p>${E(business.policy||L.unknown)}</p><p>${E(L.private)}</p></section>`;
  element.addEventListener('change',event=>{const input=event.target.closest('[data-receipt]');if(!input||!expenses.some(e=>e.id===input.dataset.receipt))return;saved[input.dataset.receipt]=input.checked;try{localStorage.setItem(storageKey,JSON.stringify(saved));element.querySelector('[data-business-storage]').hidden=true;}catch{element.querySelector('[data-business-storage]').hidden=false;}});
}
