import {initTrailMotion} from './trail-motion.mjs';
import {escapeHTML as E,safeURL,localDate,dateDistance,tripStage,countdown,duration,formatTime,formatDay,nextFlightIndex,pendingTickets,initialState,normalizeState,visibleTasks,taskStats} from './core.mjs';

const $=s=>document.querySelector(s);
const icons={plane:'<path d="m3 12 7-2V4c0-2 4-2 4 0v6l7 2v3l-7-1v5l3 2H7l3-2v-5l-7 1v-3Z"/>',arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',train:'<rect x="5" y="3" width="14" height="15" rx="3"/><path d="M5 10h14M8 21l2-3m6 3-2-3M9 14h.01M15 14h.01"/>',bus:'<rect x="4" y="4" width="16" height="15" rx="2"/><path d="M4 11h16M8 15h.01M16 15h.01M7 19v2m10-2v2"/>',walk:'<circle cx="13" cy="4" r="2"/><path d="m8 12 3-5 4 4 4 1m-8-4-1 7-4 6m4-6 5 3 1 4"/>',hotel:'<path d="M4 20V5h16v15M9 20v-5h6v5M8 8h1m6 0h1M8 11h1m6 0h1"/>',check:'<path d="m5 12 4 4L19 6"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2.5"/>',external:'<path d="M14 4h6v6m0-6L10 14M10 4H4v16h16v-6"/>',expand:'<path d="M9 3H3v6m12-6h6v6M3 15v6h6m12-6v6h-6"/>',copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M15 8V3H3v13h5"/>',print:'<path d="M6 8V3h12v5M6 17H3V8h18v9h-3M6 14h12v7H6Z"/>',share:'<path d="M12 15V3m-4 4 4-4 4 4M5 12v8h14v-8"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',taxi:'<path d="m4 9 2-5h12l2 5v9H4V9Zm0 0h16M7 18v3m10-3v3M7 13h1m8 0h1"/>'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.pin}</svg>`;
let data,places,sources,tickets,hotels,state,storageKey,filter='todo',activeTab=0,activeFlight=0;
let toastTimer,activeDialog=null,dialogOpener=null,savedScroll=0,mapSequence=0,savedScrollRestoration;
const routeArtwork={asset:'assets/route-overview-ai.png?v=20260908-no-footer',width:1024,height:1536};
const pad=n=>String(n).padStart(2,'0');
const shortDate=date=>`${Number(date.slice(5,7))}月${Number(date.slice(8,10))}日`;
function sourceLinks(ids=[]){return `<div class="source-links">${[...new Set(ids)].map(id=>sources[id]).filter(s=>s?.url&&safeURL(s.url)).map(s=>`<a class="source-link" href="${E(safeURL(s.url))}" target="_blank" rel="noopener noreferrer">${E(s.title)} ↗</a>`).join('')}</div>`;}
function chip(id){const p=places[id];return p?`<button type="button" class="place-chip" data-place="${E(id)}" aria-label="查看${E(p.name)}地图"><span class="pin" aria-hidden="true">●</span>${E(p.name)}</button>`:'';}
function chips(ids=[]){return `<div class="place-chips">${[...new Set(ids)].map(chip).join('')}</div>`;}
function sectionHead(key,meta=''){const [en,zh]=data.ui.sections[key];return `<div class="section-head"><div>${en?`<p class="eyebrow">${E(en)}</p>`:''}<h2>${E(zh)}</h2></div><div class="section-meta" ${key==='flights'?'id="flight-counter"':''}>${meta}</div></div>`;}
function getState(){try{return normalizeState(JSON.parse(localStorage.getItem(storageKey)||'null'));}catch{return initialState();}}
function saveState(){try{localStorage.setItem(storageKey,JSON.stringify(state));$('#storage-warning').hidden=true;}catch{$('#storage-warning').hidden=false;}}
function toast(text,action){clearTimeout(toastTimer);const el=$('#toast');el.replaceChildren();const t=document.createElement('span');t.textContent=text;el.append(t);if(action){const b=document.createElement('button');b.type='button';b.textContent='撤销';b.addEventListener('click',()=>{action();el.replaceChildren();});el.append(b);}toastTimer=setTimeout(()=>el.replaceChildren(),action?6500:2700);}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('已复制');}catch{const input=document.createElement('textarea');input.value=text;input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();let ok=false;try{ok=document.execCommand('copy');}catch{}input.remove();toast(ok?'已复制':'复制不可用，请长按选中文字');}}

function airportHTML(a,side){return `<div class="airport ${side}"><div class="iata">${E(a.code)}</div><div class="city-name">${E(a.city)}</div><div class="terminal">${E(a.terminal||'')}</div></div>`;}
function transportFlightEndpoint(airport,at,label){return `<div class="transport-flight-endpoint" data-flight-at="${E(at)}" data-flight-zone="${E(airport.timeZone)}" data-flight-zone-label="${E(airport.timeZoneLabel)}"><div class="transport-flight-meta"><span>${label}</span><span class="transport-flight-date">${formatDay(at,airport.timeZone)}</span></div><h3>${E(airport.city)}<small>${E(airport.code)}</small></h3><time datetime="${E(at)}">${formatTime(at,airport.timeZone)}</time><p class="transport-flight-zone">${E(airport.timeZoneLabel)}</p><p class="transport-flight-terminal">${E(airport.terminal||'')}</p></div>`;}
function transportFlightNotesHTML(f){
 const day=data.days.find(d=>d.events.some(e=>e.departure===f.segments[0].departure));
 const guidance=(day?.events||[]).filter(e=>e.kind==='airport'||e.kind==='transfer');
 const refs=[...new Set([...f.sourceRefs,...guidance.flatMap(e=>e.sourceRefs||[])])];
 const placeIds=[...new Set(guidance.flatMap(e=>e.placeIds||[]))];
 const body=guidance.length?guidance.map(e=>`<div class="transport-flight-tip"><h4>${E(e.timeLabel)}</h4><p>${E(e.kind==='transfer'?e.shortSummary:e.notes)}</p>${e.details?.length&&e.kind!=='airport'?`<p>${E(e.details[0])}</p>`:e.kind==='airport'&&e.details?.some(t=>t.includes('成田空港'))?`<p>${E(e.details.find(t=>t.includes('成田空港')))}</p>`:''}</div>`).join(''):f.notes.filter(n=>!n.includes('已由用户确认出票')).map(n=>`<p>${E(n)}</p>`).join('');
 return `<details class="flight-notes" open><summary>出发与抵达提示</summary>${body}<div class="transport-flight-actions">${placeIds.map(id=>places[id]?`<button type="button" data-place="${E(id)}">${icon('pin')}<span>${E(places[id].name)}</span></button>`:'').join('')}${refs.map(id=>sources[id]?.url?`<a href="${E(safeURL(sources[id].url))}" target="_blank" rel="noopener noreferrer"><span>${E(sources[id].title)}</span>${icon('external')}</a>`:'').join('')}</div></details>`;
}
function transportDirectFlightHTML(f,index){const first=f.segments[0];return `<article class="flight-card transport-flight-card" data-flight="${index}" aria-label="第${index+1}趟航班，${E(f.label)}"><div class="transport-ticket"><div class="transport-ticket-main"><div class="transport-ticket-masthead"><span>登机牌</span><small>BOARDING PASS</small><span>${pad(index+1)}</span></div><div class="transport-flight-top"><span>${E(f.airline)} <b>${E(first.number)}</b></span><span class="confirmed">${icon('check')}已出票</span></div><div class="transport-flight-route">${transportFlightEndpoint(first.origin,first.departure,'出发')}<span class="transport-flight-arrow" aria-hidden="true">${icon('plane')}</span>${transportFlightEndpoint(first.destination,first.arrival,'抵达')}</div><div class="transport-flight-duration"><span>直飞 · ${duration(first.departure,first.arrival)}</span><button type="button" data-flight-time aria-pressed="false">统一北京时间 ⇄</button></div><p class="transport-flight-clock-note">起降各用当地时间</p></div><div class="transport-ticket-stub"><div class="countdown-area"><p class="countdown-label">距起飞</p><div class="countdown" data-countdown="${E(first.departure)}" aria-live="off"></div></div></div></div>${transportFlightNotesHTML(f)}</article>`;}

function flightHTML(f,index){if(f.segments.length===1)return transportDirectFlightHTML(f,index);const first=f.segments[0],last=f.segments.at(-1);const stops=[first.origin,...f.segments.map(s=>s.destination)];const multi=stops.length>2;return `<article class="flight-card" data-flight="${index}" aria-label="第${index+1}趟航班，${E(f.label)}"><div class="flight-top"><div><div class="flight-index">FLIGHT ${pad(index+1)} / ${pad(data.flightJourneys.length)}</div><p class="carrier">${E(f.airline)}</p></div><span class="confirmed">${icon('check')}已出票</span></div><p class="journey-name">${E(f.label)}</p><div class="flight-path ${multi?'multi':''}" ${multi?`style="--stop-count:${stops.length}"`:''}>${multi?stops.map((a,i)=>airportHTML(a,i===stops.length-1?'last':i?'mid':'first')).join(''):airportHTML(first.origin,'first')+`<div class="flight-link">${icon('plane')}<span>${E(first.number)}</span></div>`+airportHTML(last.destination,'last')}</div><div class="flight-schedule"><div><div class="schedule-date">${formatDay(first.departure,first.origin.timeZone)} · 出发</div><div class="schedule-time">${formatTime(first.departure,first.origin.timeZone)}</div><div class="schedule-zone">${E(first.origin.timeZoneLabel)}</div></div><div><div class="schedule-date">${formatDay(last.arrival,last.destination.timeZone)} · 抵达</div><div class="schedule-time">${formatTime(last.arrival,last.destination.timeZone)}</div><div class="schedule-zone">${E(last.destination.timeZoneLabel)}</div></div></div>${multi?f.segments.map((s,i)=>`<div class="flight-via">${E(s.number)} · ${E(s.origin.code)} ${formatTime(s.departure,s.origin.timeZone)} → ${E(s.destination.code)} ${formatTime(s.arrival,s.destination.timeZone)}${i<f.segments.length-1?`<br>中转停留 ${duration(s.arrival,f.segments[i+1].departure)}`:''}</div>`).join(''):''}<p class="flight-duration">${duration(first.departure,last.arrival)} · ${multi?'含中转':'直飞'}</p><div class="countdown-area"><p class="countdown-label">距离起飞还剩</p><div class="countdown" data-countdown="${E(first.departure)}" aria-live="off"></div></div><details class="flight-notes"><summary>航班备注与时间说明</summary>${f.notes.map(x=>`<p>${E(x)}</p>`).join('')}${sourceLinks(f.sourceRefs)}</details></article>`;}
function flightsHTML(){const selected=nextFlightIndex(data.flightJourneys);return `<div class="flight-document" id="flight-document"><div class="transport-flight-heading"><h3>航班<small>往返已出票</small></h3><span id="flight-counter">${selected+1} / ${data.flightJourneys.length}</span></div><div class="flight-document-body"><div class="transport-flight-picker" role="group" aria-label="选择往返航班">${data.flightJourneys.map((f,i)=>`<button type="button" data-flight-to="${i}" aria-label="查看${E(f.label)}" aria-current="${i===selected}">${E(f.id==='outbound'?'去程':f.label.split(' · ')[0])}<small>${formatDay(f.segments[0].departure,f.segments[0].origin.timeZone)}</small><span class="transport-flight-bookmark" aria-hidden="true"></span></button>`).join('')}</div><div class="flight-rail" id="flight-rail" role="region" aria-label="横向滑动查看航班" tabindex="0">${data.flightJourneys.map(flightHTML).join('')}</div><div class="dots" role="group" aria-label="选择航班">${data.flightJourneys.map((_,i)=>`<button class="dot-button" type="button" data-flight-to="${i}" aria-label="查看第${i+1}趟航班" aria-current="${i===selected}"><span></span></button>`).join('')}</div></div></div>`;}

function routeHTML(){const ids=[...new Set([...data.routeMap.overviewIds,...data.routeMap.insetIds])];const visits=new Map();for(const day of data.days){for(const event of day.events){if(/^确认明日/.test(event.title))continue;for(const id of event.placeIds||[]){if(ids.includes(id)&&!visits.has(id))visits.set(id,day.date);}}}ids.sort((a,b)=>(visits.get(a)||'9999').localeCompare(visits.get(b)||'9999')||[...visits.keys()].indexOf(a)-[...visits.keys()].indexOf(b));const placeRows=ids.map(id=>{const p=places[id],date=visits.get(id);return `<button type="button" class="place-chip" data-place="${E(id)}" aria-label="查看${E(p.name)}地图">${date?`<time class="route-place-date" datetime="${date}">${shortDate(date)}</time>`:''}<span>${E(p.name)}</span></button>`;}).join('');return sectionHead('route')+`<figure class="route-figure route-artwork"><img src="${routeArtwork.asset}" width="${routeArtwork.width}" height="${routeArtwork.height}" alt="日本旅行插画总览：关西机场、和歌浦、熊野、名古屋、东京与成田机场；林中四位旅人与八咫乌路标" loading="lazy"></figure><span id="route-context" hidden></span><details class="route-places" open><summary><span class="route-index-title">沿途地点</span><span class="route-index-count">${ids.length} 处</span><span class="route-index-toggle" aria-hidden="true">＋</span></summary><div class="place-chips">${placeRows}</div></details>`;}


function ticketBox(t){const done=Boolean(state.tickets[t.id]);return `<div class="ticket-box ${done?'done':''}" data-ticket-box="${E(t.id)}"><label class="ticket-check"><input type="checkbox" data-ticket-check="${E(t.id)}" ${done?'checked':''} aria-label="标记${E(t.title)}已购票"><span class="ticket-main"><span class="ticket-state">${done?'已购票':E(t.mode)}</span><strong class="ticket-name">${E(t.title)}</strong>${t.optional?'<span class="ticket-note">可选</span>':''}</span></label><div class="ticket-action"><button type="button" data-ticket-info="${E(t.id)}">${icon('external')}购票指引</button>${t.price?`<span class="ticket-price">成人 ¥${Number(t.price).toLocaleString()}</span>`:''}</div></div>`;}
function eventHTML(e){return `<li class="event ${e.departure?'fixed':''}" id="${E(e.id)}"><div class="event-time">${E(e.timeLabel)}</div><div class="event-body"><h4>${E(e.title)}</h4>${e.warning?`<div class="event-warning">${icon('clock')} ${E(e.warning)}</div>`:''}${e.shortSummary?`<p class="event-brief">${E(e.shortSummary)}</p>`:''}${e.ticketIds.map(id=>tickets[id]?ticketBox(tickets[id]):'').join('')}<details class="event-detail"><summary>详情与地图</summary>${e.notes?`<p>${E(e.notes)}</p>`:''}${e.details.length?`<ul>${e.details.map(x=>`<li>${E(x)}</li>`).join('')}</ul>`:''}${chips(e.placeIds)}${sourceLinks(e.sourceRefs)}</details></div></li>`;}

function stayHTML(h){if(!h)return '';return `<section class="day-stay stay-compact"><div class="stay-folio"><span>夜宿</span><span class="day-stay-moon" aria-hidden="true"></span></div><div class="stay-copy"><div class="day-stay-heading"><h4>${E(h.name)}</h4><button type="button" class="day-stay-map" data-place="${E(h.placeId)}" aria-label="查看${E(h.name)}地图">${icon('pin')}地图</button></div>${h.placeId==='okura'?'<p class="stay-arrival-note">住宿请走5F正面入口，1F为宴会入口。</p>':''}<details class="day-stay-details"><summary>到店信息</summary>${h.localName?`<p>${E(h.localName)}</p>`:''}${h.note?`<p>${E(h.note)}</p>`:''}${sourceLinks(h.sourceRefs)}</details></div></section>`;}

const dayCoverAssets={'day-1':'assets/day-wakaura-bay.webp','day-2':'assets/day-tea-path.webp','day-4':'assets/day-tokyo-arrival.webp','day-5':'assets/day-tokyo-street.webp','day-6':'assets/day-tokyo-asakusa.webp'};
const dayCoverAlts={'day-1':'和歌浦海湾意象插画','day-2':'茶田与山路意象插画','day-4':'东京站意象插画','day-5':'东京街景意象插画','day-6':'东京浅草雷门意象插画'};
function dayHTML(d,i){const today=localDate(new Date(),data.trip.timeZone),dayAsset=dayCoverAssets[d.id]||d.imageAsset,dayTitle=d.title.replace(/至|与|返/, ' → ');return `<details class="day ${dayAsset?'day-photo':''}" id="${E(d.id)}" data-day="${E(d.id)}" data-scene-theme="${E(d.chapterTheme)}" data-soundscape="${E(d.chapterTheme==='sky'?'quiet':d.chapterTheme)}" ${d.date===today?'open':''}><summary>${dayAsset?`<div class="day-image" data-soundscape="${d.id==='day-3'?'river':d.id==='day-2'?'forest':'quiet'}" ${d.id==='day-3'?'data-living-landscape="waterfall"':''} data-image="${E(dayAsset)}"><img src="${E(dayAsset)}" alt="${E(dayCoverAlts[d.id]||'')}" loading="lazy"></div>`:''}<div class="day-summary-copy"><div class="day-heading-meta"><span>${shortDate(d.date)}</span>${d.date===today?'<span class="show-now">今天</span>':''}</div><h3>${E(dayTitle)}</h3></div><span class="expand-symbol" aria-hidden="true"></span></summary><div class="day-content"><p class="day-route-full">${E(d.routeSummary)}</p><ol class="schedule">${d.events.map(eventHTML).join('')}</ol>${stayHTML(hotels[d.accommodationId])}<button type="button" class="day-fold" data-day-fold aria-label="收起${E(dayTitle)}当天行程">收起当天 ↑</button></div></details>`;}
function itineraryHTML(){return sectionHead('itinerary')+`<div class="day-list">${data.days.map(dayHTML).join('')}</div>`;}
// Day-local action keeps the reader at the date after a long itinerary.
document.addEventListener('click',event=>{
 const button=event.target.closest('[data-day-fold]');
 if(!button)return;
 const day=button.closest('.day');
 day.open=false;
 day.querySelector(':scope > summary').focus({preventScroll:true});
 day.scrollIntoView({block:'start',behavior:'instant'});
});

function transportHTML(){return sectionHead('transport')+`<div class="transport-tabs" role="tablist" aria-label="交通信息分类">${data.groundTransport.tabs.map((tab,i)=>`<button class="transport-tab" type="button" role="tab" id="transport-tab-${i}" aria-controls="transport-panel-${i}" aria-selected="${i===0}" tabindex="${i===0?'0':'-1'}" data-transport-tab="${i}">${E(tab.title)}</button>`).join('')}</div><div id="transport-panel">${data.groundTransport.tabs.map((tab,i)=>`<div id="transport-panel-${i}" role="tabpanel" aria-labelledby="transport-tab-${i}" tabindex="0" ${i===0?'':'hidden'}>${tab.items.map(item=>`<details class="transport-item"><summary>${E(item.title)}</summary><p>${E(item.text)}</p>${chips(item.placeIds)}${sourceLinks(item.sourceRefs)}</details>`).join('')}</div>`).join('')}</div><div class="quick-source-bar">${['weather','jr-running','jr-central-running','bus-operator'].map(id=>`<a href="${E(safeURL(sources[id].url))}" target="_blank" rel="noopener noreferrer">${E(({weather:'天气', 'jr-running':'JR西日本','jr-central-running':'JR东海','bus-operator':'巴士运行'})[id])}</a>`).join('')}</div>`;}
function renderTransport(index){if(!data.groundTransport.tabs[index])return;activeTab=index;document.querySelectorAll('[data-transport-tab]').forEach((el,i)=>{el.setAttribute('aria-selected',String(i===index));el.tabIndex=i===index?0:-1;document.getElementById('transport-panel-'+i).hidden=i!==index;});}

function prepHTML(){return sectionHead('prep','<span id="prep-count"></span>')+`<div class="prep-tabs" role="group" aria-label="准备清单筛选"><button type="button" class="prep-filter" data-filter="all" aria-pressed="true">全部</button><button type="button" class="prep-filter" data-filter="todo" aria-pressed="false">待办</button><button type="button" class="prep-filter" data-filter="packing" aria-pressed="false">物品</button></div><form class="prep-form" id="prep-form"><input id="prep-input" type="text" maxlength="140" enterkeyhint="done" autocomplete="off" placeholder="添加一项准备事项" aria-label="添加准备事项"><button type="submit">添加</button></form><p class="local-note">${E(data.ui.privacyNote)}</p><p class="storage-warning" id="storage-warning" hidden>当前浏览器不能保存记录，本次修改仅在本页有效。</p><ul class="prep-list" id="prep-list"></ul>`;}
function renderPrep(){const list=visibleTasks(data.preTrip,state,filter),stats=taskStats(data.preTrip,state,filter);$('#prep-count').textContent=`${stats.completed} / ${stats.total}`;const inputLabel=filter==='packing'?'添加物品':'添加待办';$('#prep-input').placeholder=inputLabel;$('#prep-input').setAttribute('aria-label',inputLabel);document.querySelectorAll('[data-filter]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.filter===filter)));$('#prep-list').innerHTML=list.length?list.map(t=>{const done=Boolean(state.tasks[t.id]);return `<li class="prep-item ${done?'done':''}" data-task-row="${E(t.id)}"><label class="prep-check"><input type="checkbox" data-task-check="${E(t.id)}" aria-label="完成：${E(t.text)}" ${done?'checked':''}></label>${t.detail?`<details class="prep-item-copy"><summary><span class="prep-text">${E(t.text)}</span></summary><p class="prep-detail">${E(t.detail)}</p></details>`:`<div class="prep-item-copy"><span class="prep-text">${E(t.text)}</span></div>`}<button type="button" class="delete-task" data-delete-task="${E(t.id)}" aria-label="删除：${E(t.text)}">删除</button></li>`;}).join(''):'<li class="empty-list">暂无事项</li>';}

function initPrepSwipe(){
 const section=$('#prep'),groups=['all','todo','packing'];let gesture=null,suppressClickUntil=0;
 section.addEventListener('touchstart',e=>{
  if(e.touches.length!==1||!e.target.closest('.prep-tabs,.prep-list')){gesture=null;return;}
  const t=e.touches[0];gesture={x:t.clientX,y:t.clientY,dx:0,horizontal:false,vertical:false};
 },{passive:true});
 section.addEventListener('touchmove',e=>{
  if(!gesture)return;if(e.touches.length!==1){gesture=null;return;}
  const t=e.touches[0],dx=t.clientX-gesture.x,dy=t.clientY-gesture.y;gesture.dx=dx;
  if(!gesture.horizontal&&!gesture.vertical){if(Math.abs(dy)>12&&Math.abs(dy)>=Math.abs(dx))gesture.vertical=true;else if(Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.3)gesture.horizontal=true;}
  if(gesture.horizontal&&e.cancelable)e.preventDefault();
 },{passive:false});
 section.addEventListener('touchend',()=>{
  const g=gesture;gesture=null;if(!g?.horizontal)return;
  suppressClickUntil=Date.now()+450;if(Math.abs(g.dx)<50)return;
  const index=groups.indexOf(filter),next=Math.max(0,Math.min(groups.length-1,index+(g.dx<0?1:-1)));
  if(next===index)return;filter=groups[next];renderPrep();
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches)$('#prep-list').animate([{opacity:.4,transform:`translateX(${g.dx<0?12:-12}px)`},{opacity:1,transform:'translateX(0)'}],{duration:180,easing:'ease-out'});
 },{passive:true});
 section.addEventListener('touchcancel',()=>{gesture=null;},{passive:true});
 section.addEventListener('click',e=>{if(Date.now()<suppressClickUntil){e.preventDefault();e.stopPropagation();}},{capture:true});
 $('.prep-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const index=groups.indexOf(filter);filter=groups[e.key==='Home'?0:e.key==='End'?2:Math.max(0,Math.min(2,index+(e.key==='ArrowRight'?1:-1)))];renderPrep();section.querySelector(`[data-filter="${filter}"]`).focus();});
}

function focusPrepTask(id){const input=[...document.querySelectorAll('[data-task-check]')].find(el=>el.dataset.taskCheck===id);(input||$('#prep-input')).focus({preventScroll:true});}
function deletePrepTask(id){
 const list=visibleTasks(data.preTrip,state,filter),index=list.findIndex(t=>t.id===id),previousFilter=filter;
 if(index<0)return;
 const nextId=(list[index+1]||list[index-1])?.id;
 if(!state.deletedTaskIds.includes(id))state.deletedTaskIds.push(id);
 saveState();renderPrep();focusPrepTask(nextId);
 toast('事项已删除',()=>{state.deletedTaskIds=state.deletedTaskIds.filter(x=>x!==id);filter=previousFilter;saveState();renderPrep();focusPrepTask(id);document.activeElement.closest('.prep-item')?.scrollIntoView({block:'nearest',behavior:'instant'});});
}

function updateTicketViews(){document.querySelectorAll('[data-ticket-box]').forEach(box=>{const id=box.dataset.ticketBox,done=Boolean(state.tickets[id]);box.classList.toggle('done',done);box.querySelector('input').checked=done;box.querySelector('.ticket-state').textContent=done?'已购票':tickets[id].mode;});document.querySelectorAll('[data-pending-day]').forEach(el=>{const d=data.days.find(d=>d.id===el.dataset.pendingDay),count=pendingTickets(d,state.tickets).length;el.hidden=count===0;el.textContent=`待购 ${count}`;});}
function sourcesHTML(){return `<details><summary>旅行资料与使用说明</summary><p class="method-note">核对日期：${E(data.trip.updatedAt)}。票价以各设施最新官方说明为准，现场运行可能调整；本机个人记录不等于已经完成真实出票。</p><ul class="source-list">${data.sources.map(s=>`<li>${s.url?`<a href="${E(safeURL(s.url))}" target="_blank" rel="noopener noreferrer">${E(s.title)} ↗</a>`:E(s.title)}${s.note?`<br>${E(s.note)}`:''}</li>`).join('')}</ul></details>`;}

function openDialog(el){if(!activeDialog){savedScroll=window.scrollY;savedScrollRestoration=history.scrollRestoration;history.scrollRestoration='manual';dialogOpener=document.activeElement;if(history.state?.roadbookModal)history.replaceState(null,'',location.href);history.pushState({roadbookModal:true},'',location.href);document.body.style.position='fixed';document.body.style.top=-savedScroll+'px';document.body.style.width='100%';}else activeDialog.close();activeDialog=el;el.showModal();}
function releaseDialog(){if(!activeDialog)return;activeDialog.close();activeDialog=null;mapSequence++;const frame=$('#map-frame'),blank=frame.cloneNode(false);blank.removeAttribute('src');frame.replaceWith(blank);document.body.style.position='';document.body.style.top='';document.body.style.width='';window.scrollTo({top:savedScroll,behavior:'instant'});dialogOpener?.focus?.({preventScroll:true});dialogOpener=null;setTimeout(()=>{if(!activeDialog)history.scrollRestoration=savedScrollRestoration;},0);}
function closeDialog(){if(!activeDialog)return;const modalEntry=Boolean(history.state?.roadbookModal);releaseDialog();if(modalEntry)history.back();}
function openMap(id){
 const p=places[id];if(!p)return;
 $('#map-title').textContent=p.name;$('#map-local').textContent=p.localName;$('#map-address').textContent=p.address||'请核对日文地点名与现场标识';$('#map-note').textContent=p.note||'';$('#map-source-links').innerHTML=sourceLinks(p.sourceRefs);$('#map-copy').dataset.copy=p.localName+(p.address?'\n'+p.address:'');$('#map-external').href=safeURL(p.mapUrl);$('#map-network-note').textContent=data.ui.mapNetworkNote;
 const status=$('#map-loading'),frame=$('#map-frame'),seq=++mapSequence;
 // Keep status outside the cross-origin frame: load also fires for some error pages.
 frame.parentElement.before(status);status.hidden=false;status.setAttribute('role','status');status.textContent='正在加载地点地图…';
 frame.title=p.name+' Google 地图';
 frame.onload=()=>{if(seq===mapSequence)status.textContent='若地图空白，请用下方链接在系统浏览器打开。';};
 frame.onerror=()=>{if(seq===mapSequence)status.textContent='地图未能加载，请用下方链接在系统浏览器打开。';};
 openDialog($('#map-dialog'));$('#map-dialog .dialog-content').scrollTop=0;
 let embed='';try{const u=new URL(p.embedUrl);if(u.protocol==='https:'&&['www.google.com','maps.google.com'].includes(u.hostname))embed=u.href;}catch{}
 if(embed){frame.hidden=false;frame.src=embed;setTimeout(()=>{if(activeDialog===$('#map-dialog')&&seq===mapSequence&&status.textContent==='正在加载地点地图…')status.textContent='地图加载较慢，请用下方链接在系统浏览器打开。';},7000);}
 else{frame.onload=null;frame.onerror=null;frame.removeAttribute('src');frame.hidden=true;status.textContent='暂无内嵌地图，请使用下方地点链接。';}
}
function openFullMap(){const img=$('#fullmap-image');img.src=routeArtwork.asset;img.alt=data.routeMap.title+'行程插画示意';$('#route-dialog').setAttribute('aria-label',data.routeMap.title+' · 路线图');$('#map-zoom').classList.remove('zoomed');$('#zoom-map').setAttribute('aria-pressed','false');$('#zoom-map').setAttribute('aria-label','放大路线图');openDialog($('#route-dialog'));$('#map-zoom').scrollTo(0,0);}
function openTicket(id){const t=tickets[id];if(!t)return;$('#ticket-title').textContent=t.title;$('#ticket-mode').textContent=state.tickets[id]?'已购票 · 本机记录':t.mode;$('#ticket-where').textContent=t.where;$('#ticket-guide').textContent=t.guide;$('#ticket-price').innerHTML=t.price?`¥${Number(t.price).toLocaleString()}<small>成人单价，按实际年龄出票</small>`:'';$('#ticket-japanese').textContent=t.japanese||'';$('#ticket-japanese').hidden=!t.japanese;$('#ticket-copy').hidden=!t.japanese;$('#ticket-copy').dataset.copy=t.japanese||'';$('#ticket-large').hidden=!t.japanese;$('#ticket-japanese').classList.remove('ticket-large');$('#ticket-large').textContent='放大日文';$('#ticket-sources').innerHTML=sourceLinks(t.sourceRefs);const p=places[t.placeId];$('#ticket-map').hidden=!p;if(p){$('#ticket-map').href=safeURL(p.mapUrl);$('#ticket-map').textContent='在地图中查看购票地点 ↗';}openDialog($('#ticket-dialog'));}
function updateClocks(){const now=new Date(),stage=tripStage(data.trip,now);$('#trip-status').textContent=stage.text;const current=data.days.find(d=>d.date===stage.day);$('#route-context').textContent=current?`按日期计划：${current.routeSummary}`:data.trip.subtitle;document.querySelectorAll('[data-countdown]').forEach(el=>{const c=countdown(el.dataset.countdown,now);if(!c){el.textContent='时刻待确认';return;}if(c.ended){el.textContent='起飞时刻已过';el.style.fontSize='21px';return;}el.innerHTML=`${c.days}<small>天</small>${pad(c.hours)}:${pad(c.minutes)}:${pad(c.seconds)}`;});}
function moveFlight(index,behavior='smooth'){const rail=$('#flight-rail'),card=rail.children[index];if(!card||!rail.clientWidth)return;const railRect=rail.getBoundingClientRect(),cardRect=card.getBoundingClientRect();rail.scrollTo({left:rail.scrollLeft+cardRect.left-railRect.left-(rail.clientWidth-cardRect.width)/2,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':behavior});}
function initFlights(){
 const rail=$('#flight-rail');activeFlight=nextFlightIndex(data.flightJourneys);let scheduled=false;
 const fit=()=>{if(!rail.clientWidth)return;rail.style.height=(rail.children[activeFlight].getBoundingClientRect().height+parseFloat(getComputedStyle(rail).paddingBottom))+'px';};
 const sync=()=>{scheduled=false;if(!rail.clientWidth)return;const center=rail.getBoundingClientRect().left+rail.clientWidth/2;let best=0,dist=Infinity;[...rail.children].forEach((card,i)=>{const r=card.getBoundingClientRect(),delta=Math.abs(r.left+r.width/2-center);if(delta<dist){dist=delta;best=i;}});activeFlight=best;$('#flight-counter').textContent=`${best+1} / ${data.flightJourneys.length}`;document.querySelectorAll('[data-flight-to]').forEach(el=>el.setAttribute('aria-current',String(Number(el.dataset.flightTo)===best)));fit();};
 const restore=()=>{if(!rail.clientWidth)return;moveFlight(activeFlight,'instant');sync();};
 rail.addEventListener('click',e=>{const button=e.target.closest('[data-flight-time]');if(!button)return;const unified=button.getAttribute('aria-pressed')!=='true',card=button.closest('.flight-card');button.setAttribute('aria-pressed',String(unified));button.textContent=unified?'恢复各地时间 ↗':'统一北京时间 ⇄';card.querySelectorAll('[data-flight-at]').forEach(endpoint=>{const zone=unified?'Asia/Shanghai':endpoint.dataset.flightZone;endpoint.querySelector('time').textContent=formatTime(endpoint.dataset.flightAt,zone);endpoint.querySelector('.transport-flight-date').textContent=formatDay(endpoint.dataset.flightAt,zone);endpoint.querySelector('.transport-flight-zone').textContent=unified?'北京时间':endpoint.dataset.flightZoneLabel;});card.querySelector('.transport-flight-clock-note').textContent=unified?'两端已统一为北京时间':'起降各用当地时间';});
 rail.addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(sync);}},{passive:true});
 rail.addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const last=data.flightJourneys.length-1;moveFlight(e.key==='Home'?0:e.key==='End'?last:Math.max(0,Math.min(last,activeFlight+(e.key==='ArrowRight'?1:-1))));}});
 let previousWidth=0;new ResizeObserver(()=>{const width=rail.clientWidth;if(width!==previousWidth){previousWidth=width;if(width)requestAnimationFrame(restore);}}).observe(rail);
 const cardObserver=new ResizeObserver(fit);[...rail.children].forEach(card=>cardObserver.observe(card));
 restore();
}
function setNavActive(id){document.querySelectorAll('.bottom-nav a').forEach(a=>{const active=a.hash==='#'+id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}
function jumpHash(){
 const hash=decodeURIComponent(location.hash.slice(1)),target=document.getElementById(hash||'top');if(!target)return;
 const home=hash===''||hash==='top',page=home?'top':target.closest('main>.section')?.id;
 if(!home&&!page)return;
 document.body.dataset.page=page;document.body.classList.toggle('home-screen',home);$('.bottom-nav').hidden=home&&$('.cover')?.dataset.homeStage!=='icons';
 document.querySelectorAll('main>.section').forEach(section=>section.classList.toggle('is-current-page',section.id===page));setNavActive(page);
 const day=target.closest('.day');if(day)day.open=true;
 requestAnimationFrame(()=>{if(home||target.id===page)window.scrollTo({top:0,behavior:'instant'});else target.scrollIntoView({block:'start',behavior:'instant'});});
}

function syncHeader(){document.documentElement.style.setProperty('--header-h',$('.topbar').getBoundingClientRect().height+'px');}
function initNavigation(){new ResizeObserver(syncHeader).observe($('.topbar'));$('.bottom-nav').addEventListener('click',e=>{const link=e.target.closest('a');if(link&&link.hash===location.hash){e.preventDefault();jumpHash();}});window.addEventListener('hashchange',jumpHash);window.addEventListener('popstate',()=>{if(activeDialog&&!history.state?.roadbookModal)releaseDialog();});jumpHash();}
function printDays(id){const saved=[...document.querySelectorAll('details')].map(el=>({el,open:el.open,hidden:el.hidden}));let restored=false;const restore=()=>{if(restored)return;restored=true;saved.forEach(({el,open,hidden})=>{el.open=open;el.hidden=hidden;});document.body.classList.remove('printing-day');window.removeEventListener('afterprint',restore);};document.querySelectorAll('.day').forEach(el=>{el.open=true;if(id&&el.id!==id)el.hidden=true;});document.querySelectorAll('.event-detail,.flight-notes').forEach(el=>el.open=true);if(id)document.body.classList.add('printing-day');window.addEventListener('afterprint',restore,{once:true});try{window.print();}catch(error){restore();toast('此浏览器未能打开打印，请使用系统浏览器。');}}
function initEvents(){initPrepSwipe();document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;if(el.hasAttribute('data-place')){e.preventDefault();openMap(el.dataset.place);return;}if(el.hasAttribute('data-fullmap')){openFullMap();return;}if(el.hasAttribute('data-ticket-info')){openTicket(el.dataset.ticketInfo);return;}if(el.hasAttribute('data-close-dialog')){closeDialog();return;}if(el.hasAttribute('data-flight-to')){moveFlight(Number(el.dataset.flightTo));return;}if(el.hasAttribute('data-copy')){copyText(el.dataset.copy);return;}if(el.hasAttribute('data-filter')){filter=el.dataset.filter;renderPrep();return;}if(el.hasAttribute('data-delete-task')){deletePrepTask(el.dataset.deleteTask);return;}if(el.hasAttribute('data-transport-tab')){renderTransport(Number(el.dataset.transportTab));return;}if(el.hasAttribute('data-print-day')){printDays(el.dataset.printDay);return;}if(el.hasAttribute('data-top')){location.hash='top';jumpHash();}});
 document.addEventListener('change',e=>{if(e.target.matches('[data-ticket-check]')){state.tickets[e.target.dataset.ticketCheck]=e.target.checked;saveState();updateTicketViews();}if(e.target.matches('[data-task-check]')){state.tasks[e.target.dataset.taskCheck]=e.target.checked;const row=e.target.closest('.prep-item');row.classList.toggle('done',e.target.checked);saveState();const s=taskStats(data.preTrip,state,filter);$('#prep-count').textContent=`${s.completed} / ${s.total}`;}});
 let prepComposing=false;
 $('#prep-input').addEventListener('compositionstart',()=>{prepComposing=true;});
 $('#prep-input').addEventListener('compositionend',()=>{prepComposing=false;});
 $('#prep-form').addEventListener('submit',e=>{e.preventDefault();if(prepComposing)return;const input=$('#prep-input'),text=input.value.trim();if(!text){toast('先写下一件要准备的事');input.focus();return;}if(visibleTasks(data.preTrip,state).some(t=>t.text===text)){toast('清单里已经有这项了');return;}state.addedTasks.push({id:'custom-'+(crypto.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2)),text,group:filter==='packing'?'packing':'todo',detail:''});saveState();input.value='';renderPrep();input.focus();toast('已添加到清单');});
 $('#prep-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.isComposing||prepComposing||e.keyCode===229)){e.preventDefault();e.stopPropagation();}});
 document.querySelectorAll('.dialog').forEach(d=>{d.addEventListener('cancel',e=>{e.preventDefault();closeDialog();});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientY<r.top||e.clientY>r.bottom||e.clientX<r.left||e.clientX>r.right)closeDialog();}});});
 $('#zoom-map').addEventListener('click',()=>{const on=$('#map-zoom').classList.toggle('zoomed');$('#zoom-map').setAttribute('aria-pressed',String(on));$('#zoom-map').setAttribute('aria-label',on?'路线图适配屏幕':'放大路线图');$('#map-zoom').scrollTo(0,0);});
 $('#ticket-large').addEventListener('click',()=>{const on=$('#ticket-japanese').classList.toggle('ticket-large');$('#ticket-large').textContent=on?'恢复字号':'放大日文';});
 $('#share-button').addEventListener('click',async()=>{const url=location.origin+location.pathname;if(location.protocol==='file:'){toast('当前是本地文件，发布后才能分享网址');return;}if(['127.0.0.1','localhost'].includes(location.hostname)){await copyText(url);toast('已复制本机预览地址，尚不能发给其他设备访问');return;}try{if(navigator.share)await navigator.share({title:data.ui.shareText,text:data.trip.subtitle,url});else await copyText(url);}catch(error){if(error.name!=='AbortError')await copyText(url);}});
 $('.transport-tabs').addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const last=data.groundTransport.tabs.length-1;let n=e.key==='Home'?0:e.key==='End'?last:(activeTab+(e.key==='ArrowRight'?1:-1)+last+1)%(last+1);renderTransport(n);document.querySelector(`[data-transport-tab="${n}"]`).focus();}});
}
async function init(){try{const response=await fetch('./travel-data.json?v=20260909-skip32',{cache:'no-cache'});if(!response.ok)throw new Error('无法读取行程数据');data=await response.json();places=Object.fromEntries(data.places.map(p=>[p.id,p]));sources=Object.fromEntries(data.sources.map(s=>[s.id,s]));tickets=Object.fromEntries(data.bookingsAndTickets.map(t=>[t.id,t]));hotels=Object.fromEntries(data.accommodations.map(h=>[h.id,h]));storageKey='travel-book:'+data.trip.id+':v1';state=getState();document.title=data.trip.title;$('#identity-text').textContent=data.editorial.brand;$('#identity-meta').textContent='';$('#cover-en').textContent=data.editorial.coverEyebrow;$('#cover-title').innerHTML=data.editorial.coverTitle.map(E).join('<br>');$('#river-title').textContent=data.editorial.riverTitle;$('#river-note').textContent=data.editorial.riverNote;$('#cover-meta').textContent=`${data.trip.startDate.replaceAll('-','.')}—${data.trip.endDate.slice(5).replace('-','.')} · ${data.trip.people}人`;$('#flights').innerHTML=flightsHTML();$('#route').innerHTML=routeHTML();$('#itinerary').innerHTML=itineraryHTML();$('#transport').innerHTML=transportHTML();$('#prep').innerHTML=prepHTML();$('#homeward').remove();$('#footer-label').textContent=data.ui.footer;$('#sources').innerHTML=sourcesHTML();$('#prep').append($('#sources'));$('#loading').remove();initEvents();renderTransport(0);renderPrep();$('#transport .section-head').after($('#flights'));initFlights();initNavigation();updateClocks();setInterval(updateClocks,1000);initTrailMotion();initEditorial();import('./assets/story.js?v=20260909-skip32').then(({initVisuals})=>{initVisuals();document.body.dataset.visuals='ready';}).catch(error=>{console.error('Visual layer:',error);document.body.dataset.visuals='fallback';});}catch(error){const failure=$('#loading')||document.body.appendChild(document.createElement('div'));failure.innerHTML='<h2>路书暂时没有加载成功</h2><p>请通过本地预览服务或已发布的网址打开，并确认行程数据文件可用。</p>';console.error(error);}}
function initEditorial(){const river=$('.river-interlude'),dayBody=$('#day-2 .day-content'),stay=$('#day-2 .day-stay');if(river&&dayBody){const landscape=river.querySelector('[data-living-landscape]');landscape.dataset.image='assets/day-kawayu-water.webp';landscape.querySelector('img').src=landscape.dataset.image;landscape.dataset.alt='川汤近岸流水意象插画';river.classList.add('day-river-art');dayBody.insertBefore(river,stay);}const phase=$('#trip-status');
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in-view');});},{threshold:.14});document.querySelectorAll('.day-stay,.river-interlude,.kit-illustration').forEach(el=>observer.observe(el));
}
init();
