export const escapeHTML=(value)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function safeURL(value){try{const u=new URL(value,globalThis.location?.href||'http://localhost/');return ['https:','http:','tel:'].includes(u.protocol)?u.href:'';}catch{return '';}}
export function localDate(now=new Date(),timeZone='Asia/Tokyo'){return new Intl.DateTimeFormat('sv-SE',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(now);}
export function dateDistance(from,to){return Math.round((Date.parse(to+'T00:00:00Z')-Date.parse(from+'T00:00:00Z'))/86400000);}
export function tripStage(trip,now=new Date()){const day=localDate(now,trip.timeZone),total=dateDistance(trip.startDate,trip.endDate)+1;if(day<trip.startDate)return{kind:'before',text:`距出发 ${dateDistance(day,trip.startDate)} 天`,day:null,total};if(day>trip.endDate)return{kind:'after',text:'旅程日期已结束',day:null,total};return{kind:'during',text:`行程第 ${dateDistance(trip.startDate,day)+1} 天`,day,total};}
export function countdown(iso,now=new Date()){const target=Date.parse(iso);if(!Number.isFinite(target))return null;const seconds=Math.max(0,Math.floor((target-now.getTime())/1000));return{ended:target<=now.getTime(),days:Math.floor(seconds/86400),hours:Math.floor(seconds%86400/3600),minutes:Math.floor(seconds%3600/60),seconds:seconds%60};}
export function duration(departure,arrival){const m=Math.round((Date.parse(arrival)-Date.parse(departure))/60000);if(!Number.isFinite(m)||m<0)return '';return `${Math.floor(m/60)}小时${String(m%60).padStart(2,'0')}分`;}
export function formatTime(iso,tz){return new Intl.DateTimeFormat('zh-CN',{timeZone:tz,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(iso));}
export function formatDay(iso,tz){return new Intl.DateTimeFormat('zh-CN',{timeZone:tz,month:'numeric',day:'numeric'}).format(new Date(iso));}
export function nextFlightIndex(flights,now=new Date()){const i=flights.findIndex(f=>Date.parse(f.segments[0]?.departure)>now.getTime());return i<0?Math.max(0,flights.length-1):i;}
export function ticketIdsForDay(day){return [...new Set(day.events.flatMap(e=>e.ticketIds||[]))];}
export function pendingTickets(day,checked){return ticketIdsForDay(day).filter(id=>!checked[id]);}
export function initialState(){return{version:1,tickets:{},tasks:{},addedTasks:[],deletedTaskIds:[]};}
export function normalizeState(value){const s=initialState();if(!value||typeof value!=='object')return s;const boolMap=x=>Object.fromEntries(Object.entries(x&&typeof x==='object'?x:{}).filter(([k,v])=>typeof k==='string'&&typeof v==='boolean'));s.tickets=boolMap(value.tickets);s.tasks=boolMap(value.tasks);s.addedTasks=Array.isArray(value.addedTasks)?value.addedTasks.filter(x=>x&&typeof x.id==='string'&&typeof x.text==='string'&&x.text.length<=140).map(x=>({id:x.id,text:x.text,group:x.group==='packing'?'packing':'todo',detail:typeof x.detail==='string'?x.detail:''})):[];s.deletedTaskIds=Array.isArray(value.deletedTaskIds)?value.deletedTaskIds.filter(x=>typeof x==='string'):[];return s;}
export function visibleTasks(base,state,group='all'){const deleted=new Set(state.deletedTaskIds);return [...base,...state.addedTasks].filter(x=>!deleted.has(x.id)&&(group==='all'||x.group===group));}
export function taskStats(base,state,group='all'){const tasks=visibleTasks(base,state,group);return{total:tasks.length,completed:tasks.filter(t=>state.tasks[t.id]).length};}
